version: '3'
services:
  db:
    image: mysql:latest
    container_name: bd
    environment:
      MYSQL_ROOT_PASSWORD: usuario
      MYSQL_DATABASE: proyectoFinal
      MYSQL_USER: usuario
      MYSQL_PASSWORD: usuario 
    ports:
      - "3306:3306"
  app:
    image: tmaygon609/app
    container_name: springboot
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
  frontend:
    image: tmaygon609/frontend
    ports:
      - "80:80"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - "8081:80"
    depends_on:
      - db
